ALTER TABLE course_sessions
    ADD COLUMN IF NOT EXISTS video_title VARCHAR(255),
    ADD COLUMN IF NOT EXISTS cover_title VARCHAR(255),
    ADD COLUMN IF NOT EXISTS pdf_title VARCHAR(255),
    ADD COLUMN IF NOT EXISTS word_title VARCHAR(255);
